CREATE DATABASE IF NOT EXISTS db_mahasiswa;
USE db_mahasiswa;

CREATE TABLE IF NOT EXISTS mahasiswa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    no_induk VARCHAR(12) NOT NULL,
    nama VARCHAR(50) NOT NULL,
    jk ENUM('L','P') NOT NULL DEFAULT 'L',
    tgl_lahir DATE NOT NULL,
    alamat TEXT NOT NULL,
    dosen VARCHAR(50) NOT NULL,
    telp VARCHAR(50) DEFAULT '-'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

